<!DOCTYPE html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>運用機能</title>@vite(['resources/css/app.css','resources/js/app.js'])@include('workforce.style')</head>
<body class="bg-slate-100"><main class="workforce">
<nav><a href="{{ $dashboardUrl }}">管理画面へ</a><a href="#policy">勤務ルール・ヘルプ・休憩</a><a href="#skills">スキル</a><a href="#tasks">作業割当</a><a href="#vacancy">欠員募集</a><a href="#messages">お知らせ</a><a href="#exchange">連携・出力</a></nav>
<h1>シフト運用機能</h1>
@if(session('notice'))<p role="status" class="notice">{{ session('notice') }}</p>@endif
@if($errors->any())<div role="alert" class="error">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<section id="policy"><h2>店舗別の勤務ルール・ヘルプ・休憩</h2>
<form class="inline" method="GET"><label>店舗<select name="store_id">@foreach($stores as $s)<option value="{{ $s->id }}" @selected($store?->id === $s->id)>{{ $s->name }}</option>@endforeach</select></label><label>来店予測日<input type="date" name="date" value="{{ $date }}" required></label><button>表示</button></form>
@if($store)
<p class="muted">設定した条件を自動編成・応募承認で確認します。未設定項目は制限しません。法令への適合を判定するものではありません。</p>
<form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="policy"><input type="hidden" name="store_id" value="{{ $store->id }}">
@foreach(['max_daily_hours'=>'1日の勤務時間上限（時間）','max_weekly_hours'=>'週の勤務時間上限（月曜始まり）','max_monthly_hours'=>'月の勤務時間上限','min_rest_hours'=>'勤務間隔の下限（時間）','max_consecutive_days'=>'連続勤務日数の上限','min_monthly_days_off'=>'月の休日数の下限','break_after_hours'=>'休憩を設定する勤務時間の下限','break_minutes'=>'休憩時間（分）','customers_per_register'=>'レジ1台で対応する客数／30分'] as $key=>$label)<label>{{ $label }}<input name="{{ $key }}" type="number" step="{{ str_contains($key,'hours') ? '0.5' : '1' }}" min="0" value="{{ old($key,$policy[$key]??'') }}"></label>@endforeach
<label>休憩を避ける時間帯：開始<input type="time" name="peak_start" value="{{ $policy['peak_start']??'' }}"></label><label>終了<input type="time" name="peak_end" value="{{ $policy['peak_end']??'' }}"></label>
<label class="wide">ヘルプ候補（他店舗のスタッフを複数選択）<select multiple name="help_member_ids[]">@foreach($members->where('status','active')->where('store_id','!=',$store->id) as $m)<option value="{{ $m->id }}" @selected(in_array($m->id,$policy['help_member_ids']??[]))>#{{ $m->id }} {{ $m->displayName() }}</option>@endforeach</select></label>
<label class="wide">同時配置を避ける組合せ（スタッフIDを「1,2」の形式で1行に1組）<textarea name="excluded_pairs_text" rows="3">{{ implode("\n",array_map(fn($p)=>implode(',',$p),$policy['excluded_pairs']??[])) }}</textarea></label><button>店舗の設定を保存</button></form>
@endif</section>
<section><h2>スタッフごとの勤務条件</h2><p class="muted">入力した項目を店舗の条件より優先します。空欄は店舗の設定を使います。</p><form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="member_rules"><label>スタッフ<select name="member_id" required>@foreach($members as $m)<option value="{{ $m->id }}">{{ $m->displayName() }}</option>@endforeach</select></label>@foreach(['max_daily_hours'=>'1日の勤務上限（時間）','max_weekly_hours'=>'週の勤務上限（時間）','max_monthly_hours'=>'月の勤務上限（時間）','min_monthly_days_off'=>'月の休日数の下限'] as $key=>$label)<label>{{ $label }}<input name="{{ $key }}" type="number" min="0" step="{{ str_contains($key,'hours') ? '0.5' : '1' }}"></label>@endforeach<button>個人の条件を保存・置換</button></form>@foreach($members as $m)@if(data_get($m->profiles,'workforce_rules'))<p>{{ $m->displayName() }}：日 {{ data_get($m->profiles,'workforce_rules.max_daily_hours') ?? '店舗設定' }} / 週 {{ data_get($m->profiles,'workforce_rules.max_weekly_hours') ?? '店舗設定' }} / 月 {{ data_get($m->profiles,'workforce_rules.max_monthly_hours') ?? '店舗設定' }} / 休日 {{ data_get($m->profiles,'workforce_rules.min_monthly_days_off') ?? '店舗設定' }}</p>@endif @endforeach</section>
<section id="skills"><h2>スキル・資格登録</h2><form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="skill"><label>スタッフ<select name="member_id" required>@foreach($members as $m)<option value="{{ $m->id }}">#{{ $m->id }} {{ $m->displayName() }}</option>@endforeach</select></label><label>スキル・資格名<input name="skill" maxlength="100" required></label><label>習熟度（0〜5、0は割当不可）<input name="level" type="number" min="0" max="5" value="1" required></label><label>資格の有効期限<input name="expires_on" type="date"></label><button>登録・更新</button></form>
<div class="scroll"><table><thead><tr><th>スタッフ</th><th>スキル・資格</th><th>習熟度</th><th>期限</th></tr></thead><tbody>@forelse($skills as $skill)<tr><td>{{ $members->firstWhere('id',$skill->member_id)?->displayName() }}</td><td>{{ $skill->skill }}</td><td>{{ $skill->level }}</td><td>{{ $skill->expires_on??'なし' }}</td></tr>@empty<tr><td colspan="4">未登録です。</td></tr>@endforelse</tbody></table></div></section>
<section id="tasks"><h2>日別作業の自動割当・休憩配置</h2><p class="muted">シフトに割当済みのスタッフから、資格・習熟度・過去の同じ作業の担当回数を考慮します。まず休憩を配置してから作業を割り当ててください。</p>
<form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="task">@include('workforce.slot-select')<label>作業名<input name="name" required maxlength="100"></label><label>必要スキル（任意）<input name="skill" maxlength="100"></label><label>必要習熟度<input name="minimum_level" type="number" min="1" max="5" value="1" required></label><label>人数<input name="headcount" type="number" min="1" max="50" value="1" required></label><label>開始<input type="datetime-local" name="starts_at" required></label><label>終了<input type="datetime-local" name="ends_at" required></label><button>作業を登録</button></form>
<form method="POST" class="inline">@csrf @include('workforce.slot-select')<button name="action" value="breaks">休憩を配置</button><button name="action" value="allocate">作業を自動割当・再計算</button></form>
@foreach($tasks as $task)<div class="entry"><strong>{{ $task->name }}</strong> {{ $task->starts_at }}〜{{ $task->ends_at }} / 必要 {{ $task->headcount }}名<p>担当：@forelse($taskAssignments->where('work_task_id',$task->id) as $a) {{ $members->firstWhere('id',$a->member_id)?->displayName() }} @empty 未割当 @endforelse</p></div>@endforeach
@foreach($slots as $slot)@foreach($slot->assignments as $a)@if($a->break_starts_at)<p>休憩：{{ $a->member?->displayName() }} {{ $a->break_starts_at }}〜{{ $a->break_ends_at }}</p>@endif @endforeach @endforeach</section>
<section><h2>シフト診断・履歴から設定を推定</h2><p class="muted">独自の配置診断：100×（1−（不足人時＋過剰人時）÷必要人時）から勤務ルールの警告1件につき5点（最大30点）を減点し、0〜100点に収めます。必要人時が0・勤務時間未設定の場合は評価しません。Rシフトの独自評価やAIとは異なります。</p>
<form method="POST" class="inline">@csrf<label>対象シフト表<select name="schedule_id" required>@foreach($schedules as $s)<option value="{{ $s->id }}">#{{ $s->id }} {{ $s->starts_on->format('Y/m') }} {{ $stores->firstWhere('id',$s->store_id)?->name }}</option>@endforeach</select></label><button name="action" value="diagnose">診断する</button><button name="action" value="recommend">未設定日に履歴推定値を反映</button></form>
@if(session('diagnosis'))@php($d=session('diagnosis'))<div class="notice"><strong>配置診断：{{ $d['score'] === null ? '評価できません' : $d['score'].' / 100点' }}</strong><p>必要 {{ round($d['required'],1) }}人時 / 不足 {{ round($d['shortage'],1) }}人時 / 過剰 {{ round($d['excess'],1) }}人時</p>@foreach($d['warnings'] as $w)<p>⚠ {{ $w }}</p>@endforeach</div>@endif
<p class="muted">選択店舗の過去6か月の公開シフトから、曜日ごとに最頻の開始・終了時刻と平均配置人数を推定します。既に入力済みの日は変更しません。</p>
@forelse($recommendations as $r)<p>{{ ['日','月','火','水','木','金','土'][$r['weekday']] }}曜：{{ $r['starts_at'] }}〜{{ $r['ends_at'] }} / {{ $r['headcount'] }}名（{{ $r['samples'] }}件）</p>@empty<p>推定に使える履歴がありません。</p>@endforelse</section>
<section id="vacancy"><h2>欠員募集・他店舗ヘルプ</h2><form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="vacancy">@include('workforce.slot-select')<label>対象範囲<select name="allow_help"><option value="0">同じ店舗</option><option value="1">他店舗も含む</option></select></label><label class="wide">募集内容<textarea name="message" maxlength="2000" required></textarea></label><button>募集して対象スタッフに通知</button></form>
@foreach($vacancies as $v)<details><summary>#{{ $v->id }} {{ $v->message }}（{{ $v->status === 'open' ? '募集中' : '終了' }}）</summary>@foreach($applications->where('shift_vacancy_id',$v->id) as $a)<form method="POST" class="inline">@csrf<input type="hidden" name="action" value="accept"><input type="hidden" name="vacancy_id" value="{{ $v->id }}"><input type="hidden" name="application_id" value="{{ $a->id }}"><span>{{ $members->firstWhere('id',$a->member_id)?->displayName() }} / {{ $a->status === 'accepted' ? '採用済み' : '応募中' }}</span>@if($a->status==='pending' && $v->status==='open')<button>採用してシフトに追加</button>@endif</form>@endforeach @if($v->status==='open')<form method="POST">@csrf<input type="hidden" name="vacancy_id" value="{{ $v->id }}"><button name="action" value="close">募集を締め切る</button></form>@endif</details>@endforeach</section>
<section id="messages"><h2>本部・店舗・スタッフへのお知らせ</h2><form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="message"><label>送信先<select name="store_id"><option value="">全店舗</option>@foreach($stores as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>件名<input name="title" maxlength="150" required></label><label class="wide">本文<textarea name="body" maxlength="4000" required></textarea></label><button>お知らせを配信予約</button></form>
@forelse($messages as $m)<details><summary>{{ $m->title }} / {{ $m->created_at }} {{ $m->sender_member_id ? 'スタッフからの連絡' : '' }}</summary><pre>{{ $m->body }}</pre><p>既読 {{ $receipts->where('workforce_message_id',$m->id)->whereNotNull('read_at')->count() }} / LINE通知済み {{ $receipts->where('workforce_message_id',$m->id)->where('delivery_status','sent')->count() }} / 未配信 {{ $receipts->where('workforce_message_id',$m->id)->where('delivery_status','!=','sent')->count() }}</p></details>@empty<p>お知らせはありません。</p>@endforelse</section>
<section id="exchange"><h2>勤怠・POS・人事のCSV連携</h2><p>UTF-8のCSVを取り込みます。項目が異なる製品のデータはテンプレートに合わせて変換してください。製品固有のAPI自動連携は未接続です。</p>
<p class="muted">人事：既存スタッフIDで氏名・店舗・在籍状態を更新。勤怠：外部IDで実績を更新。POS：店舗・30分枠で実績を更新。エラーがある場合は全行を取り込みません。</p>
<nav>@foreach(['hr'=>'人事（現スタッフ一覧）','attendance'=>'勤怠テンプレート','pos'=>'POSテンプレート'] as $key=>$label)<a href="{{ $exportUrl.'?'.http_build_query(['kind'=>$key,'format'=>'csv']) }}">{{ $label }}</a>@endforeach</nav>
<form method="POST" enctype="multipart/form-data" class="grid-form">@csrf<input type="hidden" name="action" value="import"><label>種別<select name="kind"><option value="hr">人事</option><option value="attendance">勤怠実績</option><option value="pos">POS実績（30分ごと）</option></select></label><label>CSVファイル<input type="file" name="file" accept=".csv,text/csv" required></label><button>検証して取り込む</button></form>
<h2>来店客数・レジ台数の予測</h2><p class="muted">{{ $date }}：直近8週間の同じ曜日・30分枠の平均客数から推定します。レジ台数は店舗設定の処理客数で割り、切り上げます。データがない枠は予測しません。</p>
<div class="scroll"><table><thead><tr><th>時間</th><th>予測客数</th><th>レジ台数</th><th>履歴件数</th></tr></thead><tbody>@forelse($forecast as $f)<tr><td>{{ $f['time'] }}</td><td>{{ $f['customers'] }}</td><td>{{ $f['registers']??'処理客数未設定' }}</td><td>{{ $f['samples'] }}</td></tr>@empty<tr><td colspan="4">予測に使えるPOS実績がありません。</td></tr>@endforelse</tbody></table></div>
<h2>Excel・CSV出力</h2><form method="GET" action="{{ $exportUrl }}" class="grid-form"><label>内容<select name="kind"><option value="shifts">確定・編集中のシフト割当</option><option value="skills">スキル設定</option><option value="policies">店舗の運用設定</option></select></label><label>シフト表<select name="schedule_id">@foreach($schedules as $s)<option value="{{ $s->id }}">#{{ $s->id }} {{ $s->starts_on->format('Y/m') }}</option>@endforeach</select></label><label>形式<select name="format"><option value="xlsx">Excel (.xlsx)</option><option value="csv">CSV</option></select></label><button>ダウンロード</button></form></section>
</main></body></html>
