<!DOCTYPE html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>シフト・お知らせ</title>@vite(['resources/css/app.css','resources/js/app.js'])@include('workforce.style')</head><body class="bg-slate-100"><main class="workforce">
<a href="{{ route('line.availability',['tenant'=>request()->attributes->get('tenantPath')]) }}">希望シフトの提出へ</a><h1>{{ $member->displayName() }}さんのシフト・お知らせ</h1>
@if(session('notice'))<p class="notice" role="status">{{ session('notice') }}</p>@endif
@if($errors->any())<p class="error" role="alert">{{ $errors->first() }}</p>@endif
<section><h2>確定シフト・作業・休憩</h2>@forelse($slots as $slot)<div class="entry"><strong>{{ $slot->starts_at->format('n/j H:i') }}〜{{ $slot->ends_at->format('n/j H:i') }}</strong> {{ $slot->notes }}@foreach($slot->assignments as $a)@if($a->break_starts_at)<p>休憩：{{ $a->break_starts_at }}〜{{ $a->break_ends_at }}</p>@endif @endforeach @foreach($tasks->where('shift_slot_id',$slot->id) as $t)<p>{{ $t->name }}：{{ $t->starts_at }}〜{{ $t->ends_at }}</p>@endforeach</div>@empty<p>確定シフトはありません。</p>@endforelse</section>
<section><h2>欠員募集・ヘルプ</h2>@forelse($vacancies as $v)<div class="entry"><strong>{{ $v->starts_at }}〜{{ $v->ends_at }}</strong><p>{{ $v->notes }}</p><pre>{{ $v->message }}</pre>@if($applications->has($v->id))<p>応募受付済み</p>@else<form method="POST">@csrf<input type="hidden" name="action" value="apply"><input type="hidden" name="vacancy_id" value="{{ $v->id }}"><button>勤務可能として応募する</button></form>@endif</div>@empty<p>現在募集中のシフトはありません。</p>@endforelse</section>
<section><h2>お知らせ</h2>@forelse($messages as $m)<details><summary>{{ $m->title }}（{{ $m->read_at ? '既読' : '未読' }}）</summary><pre>{{ $m->body }}</pre>@unless($m->read_at)<form method="POST">@csrf<input type="hidden" name="action" value="read"><input type="hidden" name="message_id" value="{{ $m->id }}"><button>確認しました</button></form>@endunless</details>@empty<p>お知らせはありません。</p>@endforelse</section>
<section><h2>管理者へ連絡</h2><form method="POST" class="grid-form">@csrf<input type="hidden" name="action" value="message"><label>件名<input name="title" maxlength="150" required></label><label class="wide">本文<textarea name="body" maxlength="4000" required></textarea></label><button>連絡を送る</button></form></section>
</main></body></html>
